run:
  tests: false
  skip-dirs:
  - scripts
linters:
  enable-all: true
  disable:
   - gci
linters-settings:
  gocritic:
    enabled-tags:
      - style
      - experimental
      - performance
      - diagnostic
      - opinionated
